const PDFDocument = require('pdfkit');
const { getSupabase } = require('./supabase');

const BRAND = {
  black: '#2C2C2C',
  gold: '#B8965A',
  cream: '#FAF8F4',
  grey: '#6B6B6B',
  lightGrey: '#E8E3DC'
};

async function generateProgramPDF(client, weekNo, workout, nutrition, notes) {
  return new Promise((resolve, reject) => {
    const doc = new PDFDocument({ size: 'A4', margin: 50 });
    const chunks = [];

    doc.on('data', chunk => chunks.push(chunk));
    doc.on('end', () => resolve(Buffer.concat(chunks)));
    doc.on('error', reject);

    // Header bar
    doc.rect(0, 0, 595, 80).fill(BRAND.black);
    doc.font('Helvetica-Bold').fontSize(24).fillColor('#FFFFFF')
      .text('FITNESS BY MADDY', 50, 25);
    doc.font('Helvetica').fontSize(10).fillColor(BRAND.gold)
      .text(`WEEK ${weekNo} PROGRAM`, 50, 55);
    doc.fillColor(BRAND.black);

    // Client info
    doc.moveDown(3);
    doc.font('Helvetica-Bold').fontSize(14).fillColor(BRAND.gold)
      .text(`${client.name || 'Client'}  |  ${client.program}  |  Week ${weekNo}`, 50);
    doc.moveDown(0.5);
    doc.moveTo(50, doc.y).lineTo(545, doc.y).stroke(BRAND.lightGrey);
    doc.moveDown(1);

    // Workout Plan
    doc.font('Helvetica-Bold').fontSize(16).fillColor(BRAND.black)
      .text('WORKOUT PLAN');
    doc.moveDown(0.5);

    if (workout && workout.days) {
      for (const day of workout.days) {
        doc.font('Helvetica-Bold').fontSize(11).fillColor(BRAND.gold)
          .text(day.name.toUpperCase());
        doc.moveDown(0.3);

        if (day.exercises) {
          for (const ex of day.exercises) {
            doc.font('Helvetica').fontSize(10).fillColor(BRAND.grey)
              .text(`  ${ex.name}  —  ${ex.sets}x${ex.reps}  ${ex.rest || ''}`, { indent: 10 });
          }
        }
        doc.moveDown(0.5);
      }
    } else {
      doc.font('Helvetica').fontSize(10).fillColor(BRAND.grey)
        .text(JSON.stringify(workout, null, 2));
    }

    doc.moveDown(1);
    doc.moveTo(50, doc.y).lineTo(545, doc.y).stroke(BRAND.lightGrey);
    doc.moveDown(1);

    // Nutrition Plan
    doc.font('Helvetica-Bold').fontSize(16).fillColor(BRAND.black)
      .text('NUTRITION PLAN');
    doc.moveDown(0.5);

    if (nutrition && nutrition.meals) {
      for (const meal of nutrition.meals) {
        doc.font('Helvetica-Bold').fontSize(11).fillColor(BRAND.gold)
          .text(meal.name.toUpperCase());
        doc.font('Helvetica').fontSize(10).fillColor(BRAND.grey)
          .text(`  ${meal.description || meal.items || ''}`, { indent: 10 });
        doc.moveDown(0.3);
      }
      if (nutrition.macros) {
        doc.moveDown(0.5);
        doc.font('Helvetica-Bold').fontSize(10).fillColor(BRAND.black)
          .text(`Daily Targets: ${nutrition.macros.calories || '—'} kcal | P: ${nutrition.macros.protein || '—'}g | C: ${nutrition.macros.carbs || '—'}g | F: ${nutrition.macros.fat || '—'}g`);
      }
    } else {
      doc.font('Helvetica').fontSize(10).fillColor(BRAND.grey)
        .text(JSON.stringify(nutrition, null, 2));
    }

    // Notes
    if (notes) {
      doc.moveDown(1);
      doc.moveTo(50, doc.y).lineTo(545, doc.y).stroke(BRAND.lightGrey);
      doc.moveDown(1);
      doc.font('Helvetica-Bold').fontSize(14).fillColor(BRAND.black)
        .text('COACH NOTES');
      doc.moveDown(0.3);
      doc.font('Helvetica').fontSize(10).fillColor(BRAND.grey)
        .text(notes);
    }

    // Footer
    doc.moveDown(2);
    doc.font('Helvetica').fontSize(8).fillColor(BRAND.grey)
      .text('Generated by Fitness by Maddy coaching system. For personal use only.', 50, 780, { align: 'center' });

    doc.end();
  });
}

async function uploadPDF(clientId, weekNo, pdfBuffer) {
  const db = getSupabase();
  const path = `clients/${clientId}/week_${weekNo}.pdf`;

  const { data, error } = await db.storage
    .from('programs')
    .upload(path, pdfBuffer, {
      contentType: 'application/pdf',
      upsert: true
    });

  if (error) throw error;

  const { data: urlData } = db.storage
    .from('programs')
    .getPublicUrl(path);

  return urlData.publicUrl;
}

module.exports = { generateProgramPDF, uploadPDF };
