const Anthropic = require('@anthropic-ai/sdk');
const PDFDocument = require('pdfkit');
const { supabase } = require('../lib/supabase');
const { sendTemplate } = require('../lib/whatsapp');
const { parseBody, corsHeaders } = require('../lib/helpers');

const RISKY_PATTERNS = [
  /under\s*800\s*cal/i, /500\s*cal/i, /extreme\s*deficit/i,
  /clenbuterol/i, /dnp/i, /ephedra/i, /steroid/i, /sarm/i,
  /lose\s*\d{2,}\s*kg\s*in\s*\d\s*week/i
];

function containsRiskyContent(text) {
  return RISKY_PATTERNS.some(p => p.test(text));
}

async function generatePDF(workout, nutrition, clientName, weekNo) {
  return new Promise((resolve, reject) => {
    const doc = new PDFDocument({ size: 'A4', margin: 50 });
    const chunks = [];
    doc.on('data', chunk => chunks.push(chunk));
    doc.on('end', () => resolve(Buffer.concat(chunks)));
    doc.on('error', reject);

    doc.rect(0, 0, doc.page.width, 100).fill('#2C2C2C');
    doc.fill('#B8965A').fontSize(28).text('FITNESS BY MADDY', 50, 30);
    doc.fill('#FFFFFF').fontSize(14).text(`Week ${weekNo} Program - ${clientName}`, 50, 65);

    doc.fill('#2C2C2C');
    doc.moveDown(3);

    doc.fontSize(20).fill('#B8965A').text('WORKOUT PLAN', 50);
    doc.moveDown(0.5);
    doc.fontSize(11).fill('#2C2C2C');

    if (workout && workout.days) {
      for (const day of workout.days) {
        doc.moveDown(0.5);
        doc.fontSize(13).fill('#2C2C2C').text(day.name, { underline: true });
        doc.fontSize(10).fill('#6B6B6B');
        if (day.exercises) {
          for (const ex of day.exercises) {
            doc.text(`  ${ex.name} - ${ex.sets}x${ex.reps} ${ex.notes || ''}`, { indent: 20 });
          }
        }
      }
    } else {
      doc.text(JSON.stringify(workout, null, 2));
    }

    doc.addPage();
    doc.rect(0, 0, doc.page.width, 60).fill('#2C2C2C');
    doc.fill('#B8965A').fontSize(20).text('NUTRITION PLAN', 50, 20);

    doc.fill('#2C2C2C').moveDown(2);
    doc.fontSize(11);

    if (nutrition && nutrition.meals) {
      if (nutrition.calories) doc.text(`Daily Target: ${nutrition.calories} kcal`);
      if (nutrition.protein) doc.text(`Protein: ${nutrition.protein}g | Carbs: ${nutrition.carbs || '-'}g | Fats: ${nutrition.fats || '-'}g`);
      doc.moveDown();
      for (const meal of nutrition.meals) {
        doc.fontSize(12).fill('#2C2C2C').text(meal.name, { underline: true });
        doc.fontSize(10).fill('#6B6B6B');
        if (meal.items) {
          for (const item of meal.items) {
            doc.text(`  - ${item}`, { indent: 20 });
          }
        }
        doc.moveDown(0.3);
      }
    } else {
      doc.text(JSON.stringify(nutrition, null, 2));
    }

    doc.moveDown(2);
    doc.fontSize(9).fill('#C8B89A').text('Generated by Fitness by Maddy Automation', { align: 'center' });

    doc.end();
  });
}

module.exports = async function handler(req, res) {
  corsHeaders(res);
  if (req.method === 'OPTIONS') return res.status(200).end();
  if (req.method !== 'POST') return res.status(405).json({ error: 'POST only' });

  try {
    const body = await parseBody(req);
    const { client_id, week_no } = body;

    if (!client_id || !week_no) {
      return res.status(400).json({ error: 'client_id and week_no required' });
    }

    const { data: client } = await supabase
      .from('clients').select('*').eq('id', client_id).single();

    if (!client) return res.status(404).json({ error: 'Client not found' });

    const { data: recentCheckins } = await supabase
      .from('checkins')
      .select('*')
      .eq('client_id', client_id)
      .order('week_no', { ascending: false })
      .limit(2);

    const { data: prevPrograms } = await supabase
      .from('programs')
      .select('workout_plan, nutrition_plan, week_no')
      .eq('client_id', client_id)
      .order('week_no', { ascending: false })
      .limit(1);

    const anthropic = new Anthropic();
    const prompt = `You are a NASM-certified fitness program architect for "Fitness by Maddy". Generate a Week ${week_no} personalized program.

CLIENT PROFILE:
- Name: ${client.name || 'Client'}
- Program: ${client.program}
- Week: ${week_no}

RECENT CHECK-IN DATA:
${JSON.stringify(recentCheckins || [], null, 2)}

PREVIOUS PROGRAM (for progression):
${JSON.stringify(prevPrograms?.[0] || 'First week - no previous program', null, 2)}

Generate a complete weekly program with progressive overload. Return ONLY valid JSON with this structure:
{
  "workout": {
    "days": [
      {
        "name": "Day 1 - Upper Body",
        "exercises": [
          { "name": "Bench Press", "sets": 4, "reps": "8-10", "notes": "RPE 7-8" }
        ]
      }
    ],
    "rest_days": "Wednesday, Sunday",
    "cardio": "3x 20min LISS or 2x 15min HIIT"
  },
  "nutrition": {
    "calories": 2200,
    "protein": 180,
    "carbs": 220,
    "fats": 65,
    "meals": [
      {
        "name": "Meal 1 - Breakfast",
        "items": ["4 egg whites + 1 whole egg", "1 cup oats with berries", "Black coffee"]
      }
    ]
  },
  "notes": "Focus on progressive overload from last week. Increase bench press by 2.5kg."
}

RULES:
- No calorie targets below 1200 for women or 1500 for men
- No banned or dangerous supplements
- Realistic, sustainable progression only
- Adjust based on check-in compliance and energy scores`;

    const response = await anthropic.messages.create({
      model: 'claude-sonnet-4-6',
      max_tokens: 4000,
      messages: [{ role: 'user', content: prompt }]
    });

    const rawText = response.content[0].text;
    const jsonMatch = rawText.match(/\{[\s\S]*\}/);
    if (!jsonMatch) {
      return res.status(500).json({ error: 'Failed to parse program JSON from Claude' });
    }

    const programData = JSON.parse(jsonMatch[0]);

    const fullText = JSON.stringify(programData);
    if (containsRiskyContent(fullText)) {
      const { escalateClientIssue } = require('../lib/escalate');
      await escalateClientIssue(client.name, client.phone, `Week ${week_no} program flagged for risky content. Review before sending.`);
      await supabase.from('programs').insert({
        client_id, week_no,
        workout_plan: programData.workout,
        nutrition_plan: programData.nutrition,
        notes: `FLAGGED FOR REVIEW: ${programData.notes || ''}`,
        pdf_url: null
      });
      return res.status(200).json({ action: 'flagged_for_review', week_no });
    }

    const pdfBuffer = await generatePDF(
      programData.workout, programData.nutrition,
      client.name || 'Client', week_no
    );

    const filePath = `clients/${client_id}/week_${week_no}.pdf`;
    const { error: uploadError } = await supabase.storage
      .from('programs')
      .upload(filePath, pdfBuffer, { contentType: 'application/pdf', upsert: true });

    if (uploadError) {
      console.error('PDF upload error:', uploadError.message);
    }

    const { data: { publicUrl } } = supabase.storage
      .from('programs')
      .getPublicUrl(filePath);

    const { error: insertError } = await supabase.from('programs').insert({
      client_id,
      week_no,
      workout_plan: programData.workout,
      nutrition_plan: programData.nutrition,
      notes: programData.notes || '',
      pdf_url: publicUrl
    });

    if (insertError) {
      console.error('Program insert error:', insertError.message);
    }

    await sendTemplate(client.phone, 'weekly_program', [
      client.name || 'there',
      String(week_no),
      programData.notes || 'New week, new gains!'
    ]);

    await supabase.from('programs')
      .update({ whatsapp_sent_at: new Date().toISOString() })
      .eq('client_id', client_id)
      .eq('week_no', week_no);

    return res.status(200).json({ action: 'program_generated', week_no, pdf_url: publicUrl });
  } catch (err) {
    console.error('Program generation error:', err.message);
    return res.status(500).json({ error: 'Internal error' });
  }
};
