const Anthropic = require('@anthropic-ai/sdk');
const PDFDocument = require('pdfkit');
const { supabase } = require('./lib/supabase');
const { sendTemplate } = require('./lib/whatsapp');
const { isHinglishMarket } = require('./lib/market');

const UNSAFE_PATTERNS = [
  /under\s*800\s*cal/i, /500\s*cal/i, /extreme\s*cut/i,
  /clenbuterol/i, /dnp/i, /ephedra/i, /steroid/i,
  /lose\s*\d{2,}\s*kg.*week/i, /crash\s*diet/i,
];

function isSafeProgram(text) {
  return !UNSAFE_PATTERNS.some(p => p.test(text));
}

async function generatePDF(workout, nutrition, clientName, weekNo) {
  return new Promise((resolve, reject) => {
    const doc = new PDFDocument({ size: 'A4', margin: 50 });
    const chunks = [];

    doc.on('data', chunk => chunks.push(chunk));
    doc.on('end', () => resolve(Buffer.concat(chunks)));
    doc.on('error', reject);

    doc.rect(0, 0, doc.page.width, 100).fill('#2C2C2C');
    doc.fillColor('#B8965A')
      .fontSize(28)
      .text('FITNESS BY MADDY', 50, 30, { align: 'center' });
    doc.fillColor('#FFFFFF')
      .fontSize(14)
      .text(`Week ${weekNo} Program — ${clientName || 'Client'}`, 50, 65, { align: 'center' });

    doc.moveDown(3);

    doc.fillColor('#B8965A').fontSize(20).text('WORKOUT PLAN', 50);
    doc.moveDown(0.5);
    doc.fillColor('#2C2C2C').fontSize(11);

    if (workout && workout.days) {
      for (const day of workout.days) {
        doc.moveDown(0.5);
        doc.fillColor('#2C2C2C').fontSize(13).text(day.day, { underline: true });
        doc.fontSize(10).fillColor('#6B6B6B');
        if (day.focus) doc.text(`Focus: ${day.focus}`);
        if (day.exercises) {
          for (const ex of day.exercises) {
            doc.text(`  → ${ex.name}: ${ex.sets || ''} x ${ex.reps || ''} ${ex.notes || ''}`.trim());
          }
        }
        if (day.rest) doc.text(`Rest day — ${day.rest}`);
      }
    } else {
      doc.text(JSON.stringify(workout, null, 2));
    }

    doc.addPage();

    doc.rect(0, 0, doc.page.width, 60).fill('#2C2C2C');
    doc.fillColor('#B8965A').fontSize(20).text('NUTRITION PLAN', 50, 20, { align: 'center' });

    doc.moveDown(3);
    doc.fillColor('#2C2C2C').fontSize(11);

    if (nutrition && nutrition.meals) {
      if (nutrition.daily_calories) {
        doc.fontSize(12).text(`Daily Target: ${nutrition.daily_calories} kcal | Protein: ${nutrition.protein || '—'}g | Carbs: ${nutrition.carbs || '—'}g | Fats: ${nutrition.fats || '—'}g`);
        doc.moveDown(0.5);
      }
      for (const meal of nutrition.meals) {
        doc.moveDown(0.5);
        doc.fillColor('#2C2C2C').fontSize(13).text(meal.meal, { underline: true });
        doc.fontSize(10).fillColor('#6B6B6B');
        if (meal.options) {
          for (const opt of meal.options) {
            doc.text(`  → ${opt}`);
          }
        }
        if (meal.description) doc.text(`  ${meal.description}`);
      }
    } else {
      doc.text(JSON.stringify(nutrition, null, 2));
    }

    doc.moveDown(2);
    doc.fillColor('#B8965A').fontSize(9)
      .text('Generated by Fitness by Maddy | fitnessbymaddy.com', 50, doc.page.height - 50, { align: 'center' });

    doc.end();
  });
}

module.exports = async function handler(req, res) {
  if (req.method === 'OPTIONS') return res.status(200).end();
  if (req.method !== 'POST') return res.status(405).json({ error: 'POST only' });

  const authHeader = req.headers.authorization || '';
  if (authHeader !== `Bearer ${process.env.INTERNAL_API_KEY}`) {
    return res.status(401).json({ error: 'Unauthorized' });
  }

  try {
    const { client_id, week_no } = req.body;
    if (!client_id || !week_no) {
      return res.status(400).json({ error: 'Missing client_id or week_no' });
    }

    const { data: client } = await supabase
      .from('clients')
      .select('*')
      .eq('id', client_id)
      .single();

    if (!client) return res.status(404).json({ error: 'Client not found' });

    const { data: recentCheckins } = await supabase
      .from('checkins')
      .select('*')
      .eq('client_id', client_id)
      .order('week_no', { ascending: false })
      .limit(2);

    let intakeData = null;
    if (client.lead_id) {
      const { data: intakeFile } = await supabase.storage
        .from('intake-forms')
        .download(`${client.lead_id}.json`);
      if (intakeFile) {
        try {
          intakeData = JSON.parse(await intakeFile.text());
        } catch (_) {}
      }
    }

    const anthropic = new Anthropic({ apiKey: process.env.CLAUDE_API_KEY });

    const systemPrompt = `You are a certified fitness program architect for Fitness by Maddy.
You create safe, science-backed, personalized workout and nutrition plans.

RULES:
- Never prescribe below 1200 kcal/day for women or 1500 kcal/day for men
- Never recommend banned substances, steroids, or extreme protocols
- Always include rest days (minimum 1-2 per week)
- Progressive overload: increase volume/intensity gradually
- If client reports pain or injury, recommend modified exercises and flag for review
- Output must be valid JSON matching the specified schema`;

    const userPrompt = `Generate Week ${week_no} program for this client.

CLIENT PROFILE:
${JSON.stringify({ name: client.name, program: client.program, started: client.program_started_at }, null, 2)}

INTAKE DATA:
${intakeData ? JSON.stringify(intakeData, null, 2) : 'Not available'}

RECENT CHECK-INS:
${recentCheckins && recentCheckins.length > 0 ? JSON.stringify(recentCheckins, null, 2) : 'No previous check-ins (first week)'}

OUTPUT FORMAT (respond with ONLY this JSON, no markdown):
{
  "workout_plan": {
    "days": [
      {
        "day": "Monday",
        "focus": "Upper Body Push",
        "exercises": [
          { "name": "Bench Press", "sets": "4", "reps": "8-10", "notes": "2 min rest" }
        ]
      },
      { "day": "Sunday", "rest": "Active recovery — light walk or stretching" }
    ]
  },
  "nutrition_plan": {
    "daily_calories": 2000,
    "protein": 150,
    "carbs": 200,
    "fats": 67,
    "meals": [
      { "meal": "Breakfast", "options": ["4 egg whites + 1 whole egg + oats", "Greek yogurt + berries + granola"] },
      { "meal": "Lunch", "description": "Grilled chicken breast with brown rice and vegetables" }
    ]
  },
  "coach_notes": "Brief note about this week's focus and adjustments"
}`;

    const response = await anthropic.messages.create({
      model: 'claude-sonnet-4-6',
      max_tokens: 4000,
      system: systemPrompt,
      messages: [{ role: 'user', content: userPrompt }],
    });

    const rawText = response.content[0].text;

    if (!isSafeProgram(rawText)) {
      const { escalateToMaddy } = require('./lib/escalation');
      await escalateToMaddy('Unsafe program content flagged', client.phone, `Week ${week_no} generation`);
      return res.status(400).json({ error: 'Program flagged for review — unsafe content detected' });
    }

    let parsed;
    try {
      parsed = JSON.parse(rawText);
    } catch (_) {
      const jsonMatch = rawText.match(/\{[\s\S]*\}/);
      if (jsonMatch) parsed = JSON.parse(jsonMatch[0]);
      else throw new Error('Failed to parse Claude response as JSON');
    }

    const { workout_plan, nutrition_plan, coach_notes } = parsed;

    const pdfBuffer = await generatePDF(workout_plan, nutrition_plan, client.name, week_no);

    const pdfPath = `clients/${client_id}/week_${week_no}.pdf`;
    const { error: uploadErr } = await supabase.storage
      .from('programs')
      .upload(pdfPath, pdfBuffer, { contentType: 'application/pdf', upsert: true });

    if (uploadErr) {
      console.error('[generate-program] PDF upload error:', uploadErr);
    }

    const { data: urlData } = supabase.storage
      .from('programs')
      .getPublicUrl(pdfPath);

    const pdfUrl = urlData?.publicUrl || pdfPath;

    await supabase.from('programs').upsert({
      client_id,
      week_no: parseInt(week_no, 10),
      generated_at: new Date().toISOString(),
      pdf_url: pdfUrl,
      workout_plan,
      nutrition_plan,
      notes: coach_notes || null,
    }, { onConflict: 'client_id,week_no' });

    const market = require('./lib/market').detectMarket(client.phone);
    const contextNote = isHinglishMarket(market)
      ? `Week ${week_no} ka program ready hai! Check karo aur questions ho toh poochho.`
      : `Your Week ${week_no} program is ready! Review it and let us know if you have questions.`;

    await sendTemplate(client.phone, 'weekly_program', [
      client.name || 'there',
      String(week_no),
      pdfUrl,
    ]);

    await supabase.from('programs')
      .update({ whatsapp_sent_at: new Date().toISOString() })
      .eq('client_id', client_id)
      .eq('week_no', week_no);

    return res.status(200).json({ ok: true, pdf_url: pdfUrl });
  } catch (err) {
    console.error('[generate-program]', err);
    return res.status(500).json({ error: 'Program generation failed' });
  }
};
