const Anthropic = require('@anthropic-ai/sdk');
const PDFDocument = require('pdfkit');
const { getSupabase } = require('../lib/supabase');
const { sendText } = require('../lib/whatsapp');
const { maskPhone } = require('../lib/utils');
const { escalateToMaddy } = require('../lib/escalation');

const UNSAFE_PATTERNS = [
  /\b(under|below)\s*1[0-2]00\s*cal/i,
  /\b(dnp|clenbuterol|ephedra|sarms|steroids?|anavar|tren)\b/i,
  /\b(lose\s*\d{2,}\s*(kg|lbs?)\s*(in|per)\s*(1|one|a)\s*week)/i,
];

function auditProgramSafety(text) {
  for (const pattern of UNSAFE_PATTERNS) {
    if (pattern.test(text)) return pattern.source;
  }
  return null;
}

async function generatePDF(workout, nutrition, clientName, weekNo) {
  return new Promise((resolve, reject) => {
    const doc = new PDFDocument({ size: 'A4', margin: 50 });
    const chunks = [];
    doc.on('data', c => chunks.push(c));
    doc.on('end', () => resolve(Buffer.concat(chunks)));
    doc.on('error', reject);

    doc.rect(0, 0, doc.page.width, 100).fill('#2C2C2C');
    doc.font('Helvetica-Bold').fontSize(28).fillColor('#D4AF7A')
      .text('FITNESS BY MADDY', 50, 30);
    doc.font('Helvetica').fontSize(12).fillColor('#FFFFFF')
      .text(`${clientName || 'Client'} — Week ${weekNo}`, 50, 65);

    doc.moveDown(3);

    doc.fillColor('#2C2C2C').font('Helvetica-Bold').fontSize(20)
      .text('WORKOUT PLAN', 50);
    doc.moveDown(0.5);
    doc.rect(50, doc.y, 200, 2).fill('#B8965A');
    doc.moveDown(0.5);

    if (workout && workout.days) {
      for (const day of workout.days) {
        doc.fillColor('#2C2C2C').font('Helvetica-Bold').fontSize(14)
          .text(day.name || day.day || 'Day');
        doc.moveDown(0.3);
        if (day.exercises) {
          for (const ex of day.exercises) {
            doc.font('Helvetica').fontSize(11).fillColor('#6B6B6B')
              .text(`  ${ex.name} — ${ex.sets || '3'}x${ex.reps || '12'} ${ex.notes || ''}`, { indent: 10 });
          }
        }
        doc.moveDown(0.5);
      }
    } else {
      doc.font('Helvetica').fontSize(11).fillColor('#6B6B6B')
        .text(JSON.stringify(workout, null, 2));
    }

    if (doc.y > 600) doc.addPage();
    doc.moveDown(2);
    doc.fillColor('#2C2C2C').font('Helvetica-Bold').fontSize(20)
      .text('NUTRITION PLAN', 50);
    doc.moveDown(0.5);
    doc.rect(50, doc.y, 200, 2).fill('#B8965A');
    doc.moveDown(0.5);

    if (nutrition && nutrition.meals) {
      for (const meal of nutrition.meals) {
        doc.fillColor('#2C2C2C').font('Helvetica-Bold').fontSize(13)
          .text(meal.name || 'Meal');
        doc.font('Helvetica').fontSize(11).fillColor('#6B6B6B')
          .text(meal.description || meal.items || '');
        doc.moveDown(0.4);
      }
      if (nutrition.macros) {
        doc.moveDown(0.5);
        doc.font('Helvetica-Bold').fontSize(12).fillColor('#2C2C2C')
          .text(`Daily Targets: ${nutrition.macros.calories || '—'}kcal | P: ${nutrition.macros.protein || '—'}g | C: ${nutrition.macros.carbs || '—'}g | F: ${nutrition.macros.fat || '—'}g`);
      }
    } else {
      doc.font('Helvetica').fontSize(11).fillColor('#6B6B6B')
        .text(JSON.stringify(nutrition, null, 2));
    }

    doc.moveDown(3);
    doc.font('Helvetica').fontSize(9).fillColor('#C8B89A')
      .text('Generated by Fitness by Maddy coaching system. For personal use only.', 50, doc.page.height - 50);

    doc.end();
  });
}

module.exports = async function handler(req, res) {
  if (req.method !== 'POST') return res.status(405).json({ error: 'POST only' });

  try {
    const { client_id, week_no } = req.body;
    if (!client_id || !week_no) {
      return res.status(400).json({ error: 'client_id and week_no required' });
    }

    const db = getSupabase();

    const { data: client } = await db
      .from('clients')
      .select('*')
      .eq('id', client_id)
      .single();

    if (!client) return res.status(404).json({ error: 'client not found' });

    const { data: recentCheckins } = await db
      .from('checkins')
      .select('*')
      .eq('client_id', client_id)
      .order('week_no', { ascending: false })
      .limit(2);

    const { data: existingProgram } = await db
      .from('programs')
      .select('id')
      .eq('client_id', client_id)
      .eq('week_no', week_no)
      .single();

    if (existingProgram) {
      return res.status(409).json({ error: 'program already generated for this week' });
    }

    const anthropic = new Anthropic({ apiKey: process.env.CLAUDE_API_KEY });

    const checkinSummary = recentCheckins && recentCheckins.length > 0
      ? recentCheckins.map(c => `Week ${c.week_no}: weight=${c.weight}kg, waist=${c.waist}cm, compliance=${c.compliance_score}/10, energy=${c.energy}/10, issues=${c.issues || 'none'}`).join('\n')
      : 'No previous check-ins available.';

    const response = await anthropic.messages.create({
      model: 'claude-sonnet-4-6',
      max_tokens: 4000,
      messages: [{
        role: 'user',
        content: `You are a certified fitness program architect for "Fitness by Maddy". Generate a personalized Week ${week_no} program.

CLIENT PROFILE:
- Name: ${client.name || 'Client'}
- Program: ${client.program}
- Started: ${client.program_started_at}

RECENT CHECK-INS:
${checkinSummary}

RULES:
- Never recommend under 1400 calories for women or 1600 for men
- Never recommend banned substances
- Be realistic with timelines
- Match intensity to compliance and energy scores
- If energy is low (<=4), reduce volume and add recovery work

Return ONLY valid JSON with this structure:
{
  "workout": {
    "focus": "string describing this week's focus",
    "days": [
      {
        "day": "Day 1 - Push",
        "exercises": [
          { "name": "Exercise Name", "sets": "3", "reps": "10-12", "notes": "optional" }
        ]
      }
    ]
  },
  "nutrition": {
    "macros": { "calories": 2000, "protein": 150, "carbs": 200, "fat": 70 },
    "meals": [
      { "name": "Meal 1 - Breakfast", "description": "description with portions" }
    ],
    "notes": "optional weekly nutrition note"
  },
  "coach_note": "A 1-line personalized note for the client"
}`,
      }],
    });

    const rawText = response.content[0].text;

    const jsonMatch = rawText.match(/\{[\s\S]*\}/);
    if (!jsonMatch) throw new Error('Claude did not return valid JSON');

    const programData = JSON.parse(jsonMatch[0]);
    const fullText = JSON.stringify(programData);

    const safetyFlag = auditProgramSafety(fullText);
    if (safetyFlag) {
      await escalateToMaddy(
        'Unsafe program content flagged',
        client.phone,
        `Week ${week_no} program flagged for: ${safetyFlag}`
      );
      return res.status(422).json({ error: 'program flagged for review', flag: safetyFlag });
    }

    const pdfBuffer = await generatePDF(
      programData.workout,
      programData.nutrition,
      client.name,
      week_no
    );

    const pdfPath = `${client.folder_url || 'clients/' + client_id}/week_${week_no}.pdf`;
    const { error: uploadError } = await db.storage
      .from('programs')
      .upload(pdfPath, pdfBuffer, {
        contentType: 'application/pdf',
        upsert: true,
      });

    let pdfUrl = null;
    if (!uploadError) {
      const { data: urlData } = db.storage.from('programs').getPublicUrl(pdfPath);
      pdfUrl = urlData?.publicUrl || null;
    }

    const { data: program } = await db.from('programs').insert({
      client_id,
      week_no,
      generated_at: new Date().toISOString(),
      pdf_url: pdfUrl,
      workout_plan: programData.workout,
      nutrition_plan: programData.nutrition,
      notes: programData.coach_note || null,
    }).select().single();

    if (pdfUrl) {
      const note = programData.coach_note || `Your Week ${week_no} program is ready!`;
      await sendText(client.phone, `${note}\n\nDownload your program: ${pdfUrl}`, true);

      await db.from('programs')
        .update({ whatsapp_sent_at: new Date().toISOString() })
        .eq('id', program.id);
    }

    return res.json({ ok: true, program_id: program.id, pdf_url: pdfUrl });
  } catch (err) {
    console.error('Program generation error:', err.message);
    return res.status(500).json({ error: 'internal' });
  }
};
